// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIYk_IgralBOyaK3S9hS9tYseVqVIXV4I',
    appId: '1:757925016192:web:0faf95f1c1316ab9516c65',
    messagingSenderId: '757925016192',
    projectId: 'inventaris-updl',
    authDomain: 'inventaris-updl.firebaseapp.com',
    storageBucket: 'inventaris-updl.firebasestorage.app',
    measurementId: 'G-S217PWE9YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOehtSKYnmpF3NcehNN24T05lwtlaS9S4',
    appId: '1:757925016192:android:649e0588423145ad516c65',
    messagingSenderId: '757925016192',
    projectId: 'inventaris-updl',
    storageBucket: 'inventaris-updl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOzniaDXGsvR8GvzmsK80xZhaL9Ka1X8',
    appId: '1:757925016192:ios:db3601362cb9951b516c65',
    messagingSenderId: '757925016192',
    projectId: 'inventaris-updl',
    storageBucket: 'inventaris-updl.firebasestorage.app',
    iosBundleId: 'com.example.inventarisUpdl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwOzniaDXGsvR8GvzmsK80xZhaL9Ka1X8',
    appId: '1:757925016192:ios:db3601362cb9951b516c65',
    messagingSenderId: '757925016192',
    projectId: 'inventaris-updl',
    storageBucket: 'inventaris-updl.firebasestorage.app',
    iosBundleId: 'com.example.inventarisUpdl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIYk_IgralBOyaK3S9hS9tYseVqVIXV4I',
    appId: '1:757925016192:web:0762bc12cc611664516c65',
    messagingSenderId: '757925016192',
    projectId: 'inventaris-updl',
    authDomain: 'inventaris-updl.firebaseapp.com',
    storageBucket: 'inventaris-updl.firebasestorage.app',
    measurementId: 'G-EP5JGPK5DW',
  );
}
